on:
  push:

name: CI build

jobs:
  buildBuster:
    name: Create Debian Buster ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Debian Buster ISO
        id: build_buster_iso
        run: make buildDebianBuster
      - name: Test Debian Buster ISO
        id: test_buster_iso
        run: make testExampleBuster
  buildBionic:
    name: Create Ubuntu Bionic ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Ubuntu Bionic ISO
        id: build_bionic_iso
        run: make buildUbuntuBionic
      - name: Test Ubuntu Bionic ISO
        id: test_bionic_iso
        run: make testExampleBionic
  buildFocal:
    name: Create Ubuntu Focal ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Ubuntu Focal ISO
        id: build_focal_iso
        run: make buildUbuntuFocal
      - name: Test Ubuntu Focal ISO
        id: test_focal_iso
        run: make testExampleFocal
