name: CI build

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  lint:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run shellcheck
        run: |
          shellcheck create-iso.sh chroot-script.sh example/config/configure.sh

  build-bookworm:
    name: Debian Bookworm
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build image
        run: make buildDebianBookworm
      - name: Test image
        run: make testExampleBookworm

  build-noble:
    name: Ubuntu Noble
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build image
        run: make buildUbuntuNoble
      - name: Test image
        run: make testExampleNoble

  build-neon:
    name: KDE Neon
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build image
        run: make buildKdeNeon
      - name: Test image
        run: make testExampleNeon
