on:
  push:

name: CI build

jobs:
  buildBullseye:
    name: Create Debian Bullseye ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Debian Bullseye ISO
        id: build_bullseye_iso
        run: make buildDebianBullseye
      - name: Test Debian Bullseye ISO
        id: test_bullseye_iso
        run: make testExampleBullseye
  buildBionic:
    name: Create Ubuntu Bionic ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Ubuntu Bionic ISO
        id: build_bionic_iso
        run: make buildUbuntuBionic
      - name: Test Ubuntu Bionic ISO
        id: test_bionic_iso
        run: make testExampleBionic
  buildJammy:
    name: Create Ubuntu Jammy ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Ubuntu Jammy ISO
        id: build_jammy_iso
        run: make buildUbuntuJammy
      - name: Test Ubuntu Jammy ISO
        id: test_jammy_iso
        run: make testExampleJammy
  buildNeon:
    name: Create Kde Neon ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Ubuntu Jammy ISO
        id: build_neon_iso
        run: make buildKdeNeon
      - name: Test Kde Neon ISO
        id: test_neon_iso
        run: make testExampleNeon
