on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  checkout:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
  buildBullseye:
    name: Create Debian Bullseye ISO
    runs-on: ubuntu-latest
    needs:
      - checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build Debian Bullseye ISO
        id: build_bullseye_iso
        run: make buildDebianBullseye
      - name: Test Debian Bullseye ISO
        id: test_bullseye_iso
        run: make testExampleBullseye
      - name: Tag Debian Bullseye as default
        id: tag_bullseye_default_iso_builder
        run: docker tag aitorpazos/create-debian-iso:debian-bullseye aitorpazos/create-debian-iso:latest
      - name: Tag Debian Bullseye as version
        id: tag_bullseye_version_iso_builder
        run: docker tag aitorpazos/create-debian-iso:debian-bullseye aitorpazos/create-debian-iso:${{ steps.get_version.outputs.VERSION }}
      - name: Tag Debian Bullseye
        id: tag_bullseye_iso_builder
        run: docker tag aitorpazos/create-debian-iso:debian-bullseye aitorpazos/create-debian-iso:debian-bullseye-${{ steps.get_version.outputs.VERSION }}
      - name: Login into Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Debian Bullseye default
        id: push_bullseye_default_iso_builder
        run: docker push aitorpazos/create-debian-iso:debian-bullseye
      - name: Push Debian Bullseye latest
        id: push_bullseye_latest_iso_builder
        run: docker push aitorpazos/create-debian-iso:latest
      - name: Push version
        id: push_version_iso_builder
        run: docker push aitorpazos/create-debian-iso:${{ steps.get_version.outputs.VERSION }}
      - name: Push Debian Bullseye version
        id: push_bullseye_version_iso_builder
        run: docker push aitorpazos/create-debian-iso:debian-bullseye-${{ steps.get_version.outputs.VERSION }}
  buildJammy:
    name: Create Ubuntu Jammy ISO
    runs-on: ubuntu-latest
    needs:
      - checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build Ubuntu Jammy ISO
        id: build_jammy_iso
        run: make buildUbuntuJammy
      - name: Test Ubuntu Jammy ISO
        id: test_jammy_iso
        run: make testExampleJammy
      - name: Tag Ubuntu Jammy
        id: tag_jammy_iso_builder
        run: docker tag aitorpazos/create-debian-iso:ubuntu-jammy aitorpazos/create-debian-iso:ubuntu-jammy-${{ steps.get_version.outputs.VERSION }}
      - name: Login into Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Ubuntu Jammy
        id: push_jammy_iso_builder
        run: docker push aitorpazos/create-debian-iso:ubuntu-jammy
      - name: Push Ubuntu Jammy version
        id: push_jammy_version_iso_builder
        run: docker push aitorpazos/create-debian-iso:ubuntu-jammy-${{ steps.get_version.outputs.VERSION }}
  buildNeon:
    name: Create Kde Neon ISO
    runs-on: ubuntu-latest
    needs: 
      - checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build Kde Neon ISO
        id: build_neon_iso
        run: make buildKdeNeon
      - name: Test Kde Neon ISO
        id: test_neon_iso
        run: make testExampleNeon
      - name: Tag Kde Neon
        id: tag_neon_iso_builder
        run: docker tag aitorpazos/create-debian-iso:kde-neon aitorpazos/create-debian-iso:kde-neon-${{ steps.get_version.outputs.VERSION }}
      - name: Login into Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Kde Neon
        id: push_neon_iso_builder
        run: docker push aitorpazos/create-debian-iso:kde-neon
      - name: Push Kde Neon version
        id: push_neon_version_iso_builder
        run: docker push aitorpazos/create-debian-iso:kde-neon-${{ steps.get_version.outputs.VERSION }}
  doRelease:
    name: Perform release
    runs-on: ubuntu-latest
    needs: 
      - buildBullseye
      - buildJammy
      - buildNeon
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
          draft: true
          prerelease: false
